name: Check PR

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # os: [ubuntu-latest, macOS-latest]
        os: [macOS-latest]
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - uses: actions/checkout@v1
      - name: Install additional libraries (macOS)
        if: matrix.os == 'macOS-latest'
        run: |
          brew install cmake
          brew install libpng ragel
      - name: Install esy
        run: npm install -g esy@latest
      - name: Install dependencies
        run: esy install
      - name: Build
        run: esy build
      - name: Check code formatting
        run: esy dune build @fmt --root .
      - name: Build and run example
        run: |
          esy '@example' install
          esy '@example' build
          esy '@example' format
          esy '@example' start
